# Generated by Django 3.2.8 on 2021-10-30 06:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField()),
                ('aboutus', models.TextField()),
                ('comments', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(blank=True, max_length=256, null=True)),
                ('tel', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profession', models.CharField(blank=True, max_length=128, null=True)),
                ('possition', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee/')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='class/')),
                ('days', models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=32, null=True)),
                ('lessen_start_time', models.DateTimeField()),
                ('lesson_end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Support_for_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('type_of_support', models.CharField(choices=[('Sf', 'Support for students with family'), ('Sdfk', 'Support for Dormitory-based students'), ('Sh', 'support for home-based students')], max_length=128)),
                ('kind_of_support', models.CharField(choices=[('Mf', 'monthly food'), ('Mc', 'monthly cleaning supplies'), ('Hs', 'home stuff'), ('Fh', 'found home')], max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Support_for_Students/')),
            ],
        ),
    ]
