# Generated by Django 3.2.8 on 2021-10-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Activity',
        ),
    ]
