# Generated by Django 3.2.8 on 2021-10-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0005_alter_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='days',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=32, null=True),
        ),
    ]
