# Generated by Django 3.2.8 on 2021-10-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0006_alter_activity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_for_students',
            name='kind_of_support',
            field=models.CharField(choices=[('monthly food', 'monthly food'), ('monthly cleaning supplies', 'monthly cleaning supplies'), ('home stuff', 'home stuff'), ('found home', 'found home')], max_length=128),
        ),
        migrations.AlterField(
            model_name='support_for_students',
            name='type_of_support',
            field=models.CharField(choices=[('Support for students with family', 'Support for students with family'), ('Support for Dormitory-based students', 'Support for Dormitory-based students'), ('support for home-based students', 'support for home-based students')], max_length=128),
        ),
    ]
