# Generated by Django 3.2.8 on 2021-10-30 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kulder', '0007_auto_20211030_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson/')),
                ('days', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=32, null=True)),
                ('lessen_start_time', models.DateTimeField()),
                ('lesson_end_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='lessen_start_time',
            new_name='date_of_activity',
        ),
        migrations.RenameField(
            model_name='executive',
            old_name='description',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='executive',
            old_name='image',
            new_name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='days',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lesson_end_time',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='trabzon', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='trabzon', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='trabzon', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executive',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='executive',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='trabzon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executive',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='support_for_students',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='trabzon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('studentID', models.IntegerField()),
                ('_class', models.CharField(choices=[('1', 'First year'), ('2', 'Second year'), ('3', 'Third year'), ('4', 'Fouth year'), ('5', 'Fifth year'), ('6', 'Sixth year')], max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('about', models.TextField(blank=True, null=True)),
                ('residence_type', models.CharField(choices=[('Dormitory', 'Dormitory'), ('Home', 'Home')], max_length=30)),
                ('dormitory', models.CharField(blank=True, help_text='if applicable', max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=450, null=True)),
                ('university', models.CharField(default='KTÜ', max_length=150)),
                ('department', models.CharField(max_length=250)),
                ('degree_level', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Masters', 'Masters'), ('Doctorate', 'Phd')], max_length=100)),
                ('graduate', models.BooleanField(default=False)),
                ('date_graduated', models.DateTimeField(blank=True, help_text='if applicable', null=True)),
                ('profession', models.CharField(blank=True, default='Student', max_length=150, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, to='Kulder.Student'),
        ),
    ]
