# Generated by Django 3.2.8 on 2021-10-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0008_auto_20211030_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='range',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
