# Generated by Django 3.2.8 on 2021-10-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0009_lesson_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='days',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
