# Generated by Django 3.2.8 on 2021-10-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0010_alter_lesson_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
