# Generated by Django 3.2.8 on 2021-10-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0011_executive_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='experience',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
