# Generated by Django 3.2.8 on 2021-11-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0014_alter_executive_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='adress',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='tel',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
