# Generated by Django 3.2.8 on 2021-11-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0016_auto_20211103_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='tel',
            new_name='tel1',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='tel2',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
