# Generated by Django 3.2.8 on 2021-11-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0017_auto_20211103_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='adress',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='surname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
