# Generated by Django 3.2.8 on 2021-11-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0018_auto_20211103_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_for_students',
            name='type_of_support',
        ),
        migrations.AddField(
            model_name='support_for_students',
            name='ust_kategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Kulder.support_for_students'),
        ),
        migrations.AlterField(
            model_name='support_for_students',
            name='kind_of_support',
            field=models.CharField(choices=[('Support for students with family', 'Support for students with family'), ('Support for Dormitory-based students', 'Support for Dormitory-based students'), ('support for home-based students', 'support for home-based students')], max_length=128),
        ),
    ]
