# Generated by Django 3.2.8 on 2021-11-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0020_auto_20211112_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_for_students',
            name='ust_kategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kulder.category'),
        ),
    ]
