# Generated by Django 3.2.8 on 2021-11-12 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0021_alter_support_for_students_ust_kategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_for_students',
            name='ust_kategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
