# Generated by Django 3.2.8 on 2021-11-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0022_auto_20211112_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_for_students',
            name='extra_kind_of_support',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='support_for_students',
            name='kind_of_support',
            field=models.CharField(blank=True, choices=[('Support for students with family', 'Support for students with family'), ('Support for Dormitory-based students', 'Support for Dormitory-based students'), ('support for home-based students', 'support for home-based students')], max_length=128, null=True),
        ),
    ]
