# Generated by Django 3.2.8 on 2021-11-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kulder', '0023_auto_20211112_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_for_students',
            name='extra_kind_of_support',
        ),
    ]
